project:
  type: website

website:
  twitter-card: 
    title: "LMU OSSS26"
    description: "program and application process"
    image: img/OSSS25_flyer.png
    card-style: summary_large_image
  search: false
    
  title: "LMU OSSS26"
  site-url: https://lmu-osc.github.io/Open-Science-Summer-School-2026/ 
  repo-url: https://github.com/lmu-osc/Open-Science-Summer-School-2026 
  navbar:
    left:
      - href: public-lectures.qmd
        text: "Public lectures"
      - href: track1-workshops.qmd
        text: "Track 1: Open Science training"
      - href: track1-program.qmd
        text: "Track 1: Program"
      - href: track2-workshops.qmd
        text: "Track 2: Instructor training"
      - href: track2-program.qmd
        text: "Track 2: Program"
      - href: join.qmd
        text: "Join"
    pinned: true
    collapse: true
  favicon: img/LMU-OSC_favicon.jpg

margin-header: |
  ![](/img/LMU-OSC_logo.jpg){width="175"}

format:
  html:
    include-in-header:
      - file: matomo-analytics.html
    theme: 
    - cosmo
    - custom.scss
    toc: true
    css: styles.css
 

editor: source

